### ISSUE TITLE
Home 押した際に別タブに遷移するのではなく現タブを更新する

### ISSUE THREAD

**Issue by jiyuujin** [FlutterKaigi/confwebsite2021#11]
そもそも Home (Event) ボタンを設定しなければいけないのか検討する必要がありそう

**Comment by kikuchy** [comment]
url_launcherで開くと全部新しいタブになりそう感？

> Home (Event) ボタンを設定しなければいけないのか検討する必要がありそう

たしかに 🤔 
Flutter Meetupとの関連を強調したいのであれば置いておいて良いのかもと思いますが、どうだろう…
まだ開催実績がないので、Flutter Meetupの面々である（？）と主張しても良いかもしれないと思います。

**Comment by jiyuujin** [comment]
英語化対応の際に `英語` / `日本語` 切り替えボタンを追加する場合に無理して Home (Event) を存続させる必要は無さそう

**Comment by jiyuujin** [comment]
fix: https://github.com/FlutterKaigi/confwebsite2021/commit/4585506d3e7d303134595b5af4f0bb5c1bcd3b99
