### ISSUE TITLE
staffページを開くと、タブのタイトルがstaffになり、画面をTopPageに戻してもタブのタイトルが戻らない

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/confwebsite2021#33]
気がついたので起票しましたが、起票などを受け付けていなければ遠慮なくクローズしてください 🙏 

https://user-images.githubusercontent.com/17231507/131478711-f7e6de12-6cd8-41ab-b3d1-f4a5b8311c7a.mov

環境: Chrome 92.0.4515.159（Official Build） （arm64）
日時: 2021年8月31日 18時ごろ

**Comment by jiyuujin** [comment]
@koji-1009 

いえいえ、起票していただきありがとうございます。

**Comment by azihsoyn** [comment]
🙋
