### ISSUE TITLE
Proposal: Use flutter_lints

### ISSUE THREAD

**Issue by zuct** [FlutterKaigi/confwebsite2021#39]
The lint rules should be less opinionated. pedantic_mono is apparently based on flutter_lints, but contains a bunch of personal opinions. That doesn't seem to  be suitable for a project like this for a big event that will likely to attract lots of attention. So to be more in line with the standard, let's just use flutter_lints and add only some rules as needed.

**Comment by jiyuujin** [comment]
@zuct Thank you for your suggestions and we will consider it positively

**Comment by jiyuujin** [comment]
@zuct Replaced with flutter_lints, the issue was closed

**Comment by mightyfrog** [comment]
This project uses pedantic_mono, an extension to flutter_lints.
