### ISSUE TITLE
イベントの問い合わせ先

### ISSUE THREAD

**Issue by jiyuujin** [FlutterKaigi/confwebsite2021#4]
ご意見等あればお願いします！

**Comment by jiyuujin** [comment]
[Googleフォーム](https://docs.google.com/forms/d/e/1FAIpQLSemYPFEWpP8594MWI4k3Nz45RJzMS7pz1ufwtnX4t3V7z2TOw/viewform) を作成しました

@kikuchy @mightyfrog こちら、いかがでしょ？

FlutterKaigi 用アカウントから入っていただくと編集可能なので適宜 mm

**Comment by kikuchy** [comment]
問い合わせ内容は長文入力のほうが良いかなと思ったのでそうしました！
他大丈夫だと思います！ :lgtm:

**Comment by jiyuujin** [comment]
解決したので close します
