### ISSUE TITLE
ライセンス表記について

### ISSUE THREAD

**Issue by organic-nailer** [FlutterKaigi/confwebsite2021#45]
Flutter Webで公開している場合`showAboutDialog()`等でのライセンス表記がサイト上のどこかに必要ではないかと思うのですが、どうでしょうか？
ライセンス周りはあまり理解できていないので、詳しい方がいれば回答お願いします🙏

**Comment by jiyuujin** [comment]
@organic-nailer 

ランセンス表記について issue 提起していただきありがとうございます
作成することを考慮しながら前向きに検討したいと思います
